### PR TITLE
adding in missing olmconfig file

### PR DESCRIPTION
**Pull request by acornett21**
Issue #, if available:
- Fixes: aws-controllers-k8s/community#1099
  
Description of changes:
adding in the missing olmconfig file

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

Signed-off-by: Adam D. Cornett <adc@redhat.com>

### CODE REVIEW

**Comment by A-Hilaly** [comment]
@acornett21 This will have to wait for quiet some time :/ this controller is still using `github.com/aws-controllers-k8s/runtime v0.0.6`

/hold

**Comment by acornett21** [comment]
@jaypipes @A-Hilaly I also tried to update the `runtime` to `0.15.2` for this project to validate the outputed CSV when the `olmconfig` file is present, however I ran into issues. 

1. The `/queue/sdk.go` file is incomplete on generations and throws compile errores. the `sdkFind` method is not fully implemented, and I'm not sure where this method gets generated from to fix.
2. The `test-infra` project does not seem to have `sqs` tests so I could not validate that updating to `0.15.2` actually would work, with the above compile errors fixed.

**Comment by A-Hilaly** [comment]
>I also tried to update the runtime to 0.15.2 for this project to validate the outputed CSV when the olmconfig file is present, however I ran into issues.

We are aware of the issues with sqs and sns controllers (Both of the APIs uses a map of attributes and not structs like most of the apis)

> The /queue/sdk.go file is incomplete on generations and throws compile errores. the sdkFind method is not fully implemented, and I'm not sure where this method gets generated from to fix.

This is correct, and it's quiet normal that the code-generator panics. The part generating `sdk.go` for attributes is not up to date and need some rework/updates. Some of the original code bits can be found here:
- https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/code/set_sdk.go#L124-L167
- https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/code/set_sdk.go#L371
- https://github.com/aws-controllers-k8s/code-generator/blob/main/pkg/generate/code/set_sdk.go#L556

>The test-infra project does not seem to have sqs tests so I could not validate that updating to 0.15.2 actually would work, with the above compile errors fixed.

That's correct. We will need to add `sqs` to test-infra `jobs_config.yaml` and regenerate the prow jobs https://github.com/aws-controllers-k8s/test-infra/blob/main/prow/jobs/jobs_config.yaml#L7

**Comment by acornett21** [comment]
@A-Hilaly Thanks for all the info, but wanted to clarify the below

> This is correct, and it's quite normal that the code-generator panics. 
It's not the `code-generator` that throws a panic, code generation is fine, it's `building` the `sqs-controller` since the `sdk.go` file in that project has compile errors _after_ code generation. (Probably due to the map vs struct issue you mentioned)

**Pull request merged**
